2025-07-10 17:20:10,322 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Grocery Category', 'with_parent': '1', 'cached_timestamp': '2025-07-10 15:52:54.004230', 'cmd': 'frappe.desk.form.load.getdoctype'}
2025-07-10 17:30:32,585 ERROR frappe Error while inserting deferred Error Log record: Error Log ce5lajqt70: 'Title' ([Errno 2] No such file or directory: '/home/kesav/library-bench/apps/library_management/library_management/library_management/doctype/grocery_category') will get truncated, as max characters allowed is 140
Site: library.localhost
Form Dict: {}
2025-07-10 19:34:37,689 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:34:41,978 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-01 00:00:00', 'end': '2025-07-13 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:34:48,227 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:35:06,018 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:35:16,522 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:36:02,581 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:36:41,895 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:36:52,617 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-01 00:00:00', 'end': '2025-07-13 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-10 19:36:55,192 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-11 10:25:03,860 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-11 10:26:52,561 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-11 10:27:51,661 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-11 10:28:51,389 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-11 10:29:25,589 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Workshop Calendar Grantt', 'start': '2025-06-29 00:00:00', 'end': '2025-08-10 00:00:00', 'filters': '[]', 'field_map': '{"id":"name","start":"start","end":"end","allDay":"all_day","convertToUserTz":"convert_to_user_tz"}', 'cmd': 'frappe.desk.calendar.get_events'}
2025-07-11 17:13:44,057 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"name":"Swiggy Report","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":0,"report_name":"Swiggy Report","ref_doctype":"Swiggy","reference_report":null,"is_standard":"No","module":"Library Management","report_type":"Query Report","letter_head":null,"add_total_row":0,"disabled":0,"prepared_report":0,"add_translate_data":0,"timeout":0,"query":"select * from`tabArticle`;","report_script":null,"javascript":null,"json":{},"doctype":"Report","filters":[],"roles":[{"name":"cc8i0masuv","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":1,"role":"System Manager","parent":"Swiggy Report","parentfield":"roles","parenttype":"Report","doctype":"Has Role","__unsaved":1}],"columns":[],"__last_sync_on":"2025-07-11T11:40:24.068Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-11 17:14:05,411 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"name":"Swiggy Report","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":0,"report_name":"Swiggy Report","ref_doctype":"Swiggy","reference_report":null,"is_standard":"No","module":"Library Management","report_type":"Query Report","letter_head":null,"add_total_row":0,"disabled":0,"prepared_report":0,"add_translate_data":0,"timeout":0,"query":"select * from tabArticle;","report_script":null,"javascript":null,"json":{},"doctype":"Report","filters":[],"roles":[{"name":"cc8i0masuv","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":1,"role":"System Manager","parent":"Swiggy Report","parentfield":"roles","parenttype":"Report","doctype":"Has Role","__unsaved":1}],"columns":[],"__last_sync_on":"2025-07-11T11:40:24.068Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-11 17:14:51,683 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"name":"Swiggy Report","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":0,"report_name":"Swiggy Report","ref_doctype":"Swiggy","reference_report":null,"is_standard":"No","module":"Library Management","report_type":"Query Report","letter_head":null,"add_total_row":0,"disabled":0,"prepared_report":0,"add_translate_data":0,"timeout":0,"query":"select name from tabSwiggy;","report_script":null,"javascript":null,"json":{},"doctype":"Report","filters":[],"roles":[{"name":"cc8i0masuv","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":1,"role":"System Manager","parent":"Swiggy Report","parentfield":"roles","parenttype":"Report","doctype":"Has Role","__unsaved":1}],"columns":[],"__last_sync_on":"2025-07-11T11:40:24.068Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-11 17:16:55,476 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"name":"Swiggy Report","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":0,"report_name":"Swiggy Report","ref_doctype":"Swiggy","reference_report":null,"is_standard":"No","module":"Library Management","report_type":"Query Report","letter_head":null,"add_total_row":0,"disabled":0,"prepared_report":0,"add_translate_data":0,"timeout":0,"query":"select name from tabSwiggy;","report_script":null,"javascript":null,"json":{},"doctype":"Report","filters":[],"roles":[{"name":"cc8i0masuv","owner":"Administrator","creation":"2025-07-11 17:10:23.264592","modified":"2025-07-11 17:10:23.264592","modified_by":"Administrator","docstatus":0,"idx":1,"role":"System Manager","parent":"Swiggy Report","parentfield":"roles","parenttype":"Report","doctype":"Has Role","__unsaved":1}],"columns":[],"__last_sync_on":"2025-07-11T11:40:24.068Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-12 17:33:11,481 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'data_import': 'Library Member Import on 2025-07-12 17:29:32.599183', 'google_sheets_url': 'https://docs.google.com/spreadsheets/d/1V6fp9eS_SBTDEUidPhc9kBJND6vs3B2k5Qg2VX7PPQY/edit?pli=1&gid=0#gid=0', 'cmd': 'frappe.core.doctype.data_import.data_import.get_preview_from_template'}
2025-07-12 17:45:32,284 ERROR frappe Error while inserting deferred Error Log record: Error Log cna9gcc35o: 'Title' (401 Client Error: Unauthorized for url: https://docs.google.com/spreadsheets/d/1V6fp9eS_SBTDEUidPhc9kBJND6vs3B2k5Qg2VX7PPQY/export?format=csv&gid=0) will get truncated, as max characters allowed is 140
Site: library.localhost
Form Dict: {}
2025-07-14 14:56:59,842 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'name': '1d458mnm50', 'force_send': 'true', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'pdf_generator': 'wkhtmltopdf'}
2025-07-14 14:57:22,477 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'name': '1d458mnm50', 'force_send': 'true', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'pdf_generator': 'wkhtmltopdf'}
2025-07-14 15:14:51,737 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'name': 'br6ha7o4rj', 'force_send': 'true', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'pdf_generator': 'wkhtmltopdf'}
2025-07-14 15:17:03,527 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'name': 'br6ha7o4rj', 'force_send': 'true', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'pdf_generator': 'wkhtmltopdf'}
2025-07-14 15:17:10,016 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'name': 'br6ha7o4rj', 'force_send': 'true', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'pdf_generator': 'wkhtmltopdf'}
2025-07-14 15:17:44,334 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'name': 'br6ha7o4rj', 'force_send': 'true', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'pdf_generator': 'wkhtmltopdf'}
2025-07-16 12:11:46,824 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'report_name': 'Article Report', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-07-16 12:12:05,558 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'report_name': 'Article Report', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-07-19 12:22:41,986 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"name":"LM00014","owner":"Administrator","creation":"2025-07-19 12:20:59.533131","modified":"2025-07-19 12:21:39.698482","modified_by":"Administrator","docstatus":0,"idx":0,"first_name":"Sanjay","last_name":"M","full_name":"Sanjay Mfd","email_address":"sanjay@gmail.com","phone":"+91-9874546321","doctype":"Library Member","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-19 12:40:57,182 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doctype': 'Library Member', 'with_parent': '1', 'cached_timestamp': '2025-07-17 11:25:21.941600', 'cmd': 'frappe.desk.form.load.getdoctype'}
2025-07-19 15:34:31,571 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"name":"LMS00003","owner":"Administrator","creation":"2025-07-14 18:24:45.205167","modified":"2025-07-14 18:25:39.925063","modified_by":"Administrator","docstatus":0,"idx":0,"workflow_state":"Pending HR Approval","library_member":"LM00003","full_name":"Raja R","from_date":"2025-07-03","paid":1,"doctype":"Library Membership","__last_sync_on":"2025-07-19T10:04:07.030Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-19 15:36:44,188 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"name":"LMS00003","owner":"Administrator","creation":"2025-07-14 18:24:45.205167","modified":"2025-07-14 18:25:39.925063","modified_by":"Administrator","docstatus":0,"idx":0,"workflow_state":"Pending HR Approval","library_member":"LM00003","full_name":"Raja R","from_date":"2025-07-03","paid":1,"doctype":"Library Membership","__last_sync_on":"2025-07-19T10:04:07.030Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-19 15:40:41,447 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"docstatus":0,"doctype":"Library Membership","name":"new-library-membership-lhgllcwzdg","__islocal":1,"__unsaved":1,"owner":"Administrator","paid":0,"full_name":"Hari B","library_member":"LM00011","from_date":"2025-07-19"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-19 15:41:00,351 ERROR frappe New Exception collected in error log
Site: library.localhost
Form Dict: {'doc': '{"docstatus":0,"doctype":"Library Membership","name":"new-library-membership-lhgllcwzdg","__islocal":1,"__unsaved":1,"owner":"Administrator","paid":0,"full_name":"Hari B","library_member":"LM00011","from_date":"2025-07-19"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-07-21 14:02:53,781 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:02:53,799 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:07:27,682 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:07:27,687 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:13:03,711 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:13:03,715 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:18:03,663 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:18:03,666 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:23:03,713 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:23:03,718 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:28:03,722 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:28:03,726 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:33:03,724 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:33:03,729 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:46:26,368 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:46:26,374 ERROR frappe Failed to run after request hook
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
2025-07-21 14:47:26,758 ERROR frappe Could not take error snapshot: '{' was never closed (hooks.py, line 245)
Site: library.localhost
Form Dict: {'doctype': 'File', 'fields': '["`tabFile`.`file_name`","`tabFile`.`is_private`","`tabFile`.`file_type`","`tabFile`.`file_size`","`tabFile`.`file_url`","`tabFile`.`thumbnail_url`","`tabFile`.`is_folder`","`tabFile`.`attached_to_doctype`","`tabFile`.`attached_to_name`","`tabFile`.`attached_to_field`","`tabFile`.`content_hash`","`tabFile`.`uploaded_to_dropbox`","`tabFile`.`uploaded_to_google_drive`","`tabFile`.`name`","`tabFile`.`modified`","`tabFile`.`creation`"]', 'filters': '[["File","folder","=","Home"]]', 'order_by': '`tabFile`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '', 'with_comment_count': '1'}
Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/kesav/library-bench/apps/frappe/frappe/app.py", line 197, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1308, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1619, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1588, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesav/library-bench/apps/frappe/frappe/__init__.py", line 1454, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kesav/library-bench/apps/library_management/library_management/hooks.py", line 245
    doctype_list_js = {
                      ^
SyntaxError: '{' was never closed
